AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,X-Amz-Security-Token,Authorization,X-Api-Key,X-Requested-With,Accept,Access-Control-Allow-Methods,Access-Control-Allow-Origin,Access-Control-Allow-Headers'"
      AllowOrigin: "'*'"

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      Architectures: ["arm64"]
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 5
      CodeUri: target/release/rust_lambda_deploy/
      Events:
        RustAdminControlRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: RustControlApi
            Path: "/"
            Method: POST

  FunctionApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

Outputs:
  FunctionName:
    Value: !Ref Function
    Description: Rust lambda function
